### PR TITLE
adding example file

### PR DESCRIPTION
**Pull request by fariza**
What about a simple example, just adding an extra toolbar, and also creating a new window.
I want to keep it related to the MEP27 gui elements

### CODE REVIEW

**Comment by fariza** [comment]
Can you remove the commits where you modified the toolmanager example?

**Comment by OceanWolf** [comment]
Bleugh, can't concentrate any longer, going to bed.  Just finished the save tool, including changing some of that MEP22 code I wrote earlier (which I will double check and push tomorrow).

By "remove commits" do you mean I should rebase the example out (if possible)?  or just submit a new commit that removes those changes?

P.S. please attn me, as I don't get emails about this.  Github currently only does a blanket on/off setting for all repos :(.

**Comment by OceanWolf** [comment]
Ooh, amazing!  Yes yes yes, I absolutely love this example!  Undocked toolbars FTW!

One more thing, before I merge this, any idea how to fix the focus bug?  Run the example and try to use the keyboard, to activate tools, it doesn't work... you need to press `Tab` first...

**Comment by fariza** [comment]
@OceanWolf I stumble on this problem several times.
One way to solve it is `canvas.grab_focus()`
http://matplotlib.1069221.n5.nabble.com/Cannot-get-key-press-event-to-work-with-gtk-builder-td25975.html

**Comment by OceanWolf** [comment]
Thanks, I have it fixed :).

**Pull request merged**
